# See the config map below for required config values
apiVersion: v1
kind: Namespace
metadata:
  name: tethys
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tethys-pv-volume
  namespace: tethys
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tethys-pv-claim
  namespace: tethys
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tethys-config
  namespace: tethys
data:
  TETHYS_TOKEN: "{BOT TOKEN HERE}"
  TETHYS_LOG_CHANNEL: "{MASTER LOGGING CHANNEL HERE}"
---
apiVersion: apps/v1
kind: Deployment                 
metadata:
  name: tethys-bot           
  namespace: tethys
  labels:                    
    app: tethys-bot
spec:
  replicas: 1                    
  selector:
    matchLabels:
      app: tethys-bot        
  template:                      
    metadata:
      labels:                    
        app: tethys-bot
    spec:                        
      containers:
      - name: tethys-bot
        image: catbuttes/tethys:v0.2
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: tethys-config
        volumeMounts:
        - name: tethys-persistent-storage
          mountPath: /var/lib/tethys
      volumes:
      - name: tethys-persistent-storage
        persistentVolumeClaim:
          claimName: tethys-pv-claim
      
        