name: Publish

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: catbuttes/tethys
  IMAGE_VERSION: $(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=120 --statistics
    - name: Test with unittest
      run: |
        python -m unittest
    - name: Notify on test success
      if: success()
      run: |
        IMAGE_ID=$IMAGE_NAME
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [ "$VERSION" == "master" ] && VERSION=latest
        curl -X POST -H "Content-Type: application/json" --data "{\"embeds\":[{\"title\": \"Test run complete on ${{ github.repository }} \",\"url\": \"https://github.com/${{ github.repository }}\",\"description\": \"**Publish Tests** for: $IMAGE_ID:$VERSION\nThe outcome of the run was: **${{ job.status }}** \",\"color\": 65280}]}" ${{ secrets.DISCORD_WEBHOOK }}
    - name: Notify on test failure
      if: failure()
      run: |
        IMAGE_ID=$IMAGE_NAME
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [ "$VERSION" == "master" ] && VERSION=latest
        curl -X POST -H "Content-Type: application/json" --data "{\"embeds\":[{\"title\": \"Test run complete on ${{ github.repository }} \",\"url\": \"https://github.com/${{ github.repository }}\",\"description\": \"**Publish Tests** for: $IMAGE_ID:$VERSION\nThe outcome of the run was: **${{ job.status }}** \",\"color\": 16716032‬}]}" ${{ secrets.DISCORD_WEBHOOK }}


  # Push image to GitHub Package Registry.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag image

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=$IMAGE_NAME

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      - name: Notify on publish success
        if: success()
        run: |
          IMAGE_ID=$IMAGE_NAME
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "master" ] && VERSION=latest
          curl -X POST -H "Content-Type: application/json" --data "{\"embeds\":[{\"title\": \"Publish complete on ${{ github.repository }} \",\"url\": \"https://github.com/${{ github.repository }}\",\"description\": \"**Publish Image**: $IMAGE_ID:$VERSION\nThe outcome of the publish was: **${{ job.status }}** \",\"color\": 65280}]}" ${{ secrets.DISCORD_WEBHOOK }}
      - name: Notify on publish failure
        if: failure()
        run: |
          IMAGE_ID=$IMAGE_NAME
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "master" ] && VERSION=latest
          curl -X POST -H "Content-Type: application/json" --data "{\"embeds\":[{\"title\": \"Publish failure on ${{ github.repository }} \",\"url\": \"https://github.com/${{ github.repository }}\",\"description\": \"**Publish Image**: $IMAGE_ID:$VERSION\nThe outcome of the publish was: **${{ job.status }}** \",\"color\": 16716032}]}" ${{ secrets.DISCORD_WEBHOOK }}

  deploy:
    needs: push
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up environment
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo "::set-env name=IMAGE_VERSION::$VERSION"
      
      - uses: azure/setup-kubectl@v1
        id: install
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
        id: setcontext
      - uses: Azure/k8s-deploy@v1
        with:
          namespace: 'tethys'
          manifests: |
              k8s/tethys-cd-deploy.yml
          images: catbuttes/tethys:${{env.IMAGE_VERSION}}
      - name: Notify on Deploy success
        if: success()
        run: |
          IMAGE_ID=$IMAGE_NAME
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "master" ] && VERSION=latest
          curl -X POST -H "Content-Type: application/json" --data "{\"embeds\":[{\"title\": \"Deploy complete on ${{ github.repository }} \",\"url\": \"https://github.com/${{ github.repository }}\",\"description\": \"**Deploy Image**: $IMAGE_ID:$VERSION\nThe outcome of the Deploy was: **${{ job.status }}** \",\"color\": 65280}]}" ${{ secrets.DISCORD_WEBHOOK }}
      - name: Notify on Deploy failure
        if: failure()
        run: |
          IMAGE_ID=$IMAGE_NAME
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "master" ] && VERSION=latest
          curl -X POST -H "Content-Type: application/json" --data "{\"embeds\":[{\"title\": \"Deploy failure on ${{ github.repository }} \",\"url\": \"https://github.com/${{ github.repository }}\",\"description\": \"**Deploy Image**: $IMAGE_ID:$VERSION\nThe outcome of the Deploy was: **${{ job.status }}** \",\"color\": 16716032}]}" ${{ secrets.DISCORD_WEBHOOK }}


      
